
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 14
#define YY_END_OF_BUFFER 15
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[356] =
    {   0,
        0,    0,   15,   13,    1,    1,    8,   13,    1,    8,
        8,   13,    8,    8,    8,    8,    8,    8,    8,    9,
        9,    8,    8,    8,    7,    7,   13,    8,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    8,    8,    0,   12,    0,    1,
        0,    0,    0,    0,   10,    2,    1,   10,    9,    3,
        0,    9,    9,    9,    9,    8,    8,    7,    0,    0,
        0,    0,    0,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    6,    7,    7,
        7,    7,    7,    7,    6,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    0,    0,    0,
        0,    0,   11,    0,    0,    0,    0,    0,    0,    0,
       10,    2,    0,    1,   10,    0,    9,    9,    9,    0,
        9,    9,    9,    9,    9,    0,    0,    0,    0,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    0,    0,    0,
        0,    0,    4,    4,    0,    0,    0,    0,    0,   10,
        5,    0,    0,    1,    9,    9,    9,    9,    0,    0,

        9,    0,    9,    9,    9,    0,    0,    0,    0,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        0,    0,    0,    0,    0,    0,    0,   10,    0,    9,
        9,    9,    0,   10,    9,    9,    0,    0,    0,    0,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    0,    0,    0,    0,   10,    9,
        0,    0,    0,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    0,
        0,    0,    0,    0,    7,    0,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    0,
        0,    0,    0,    7,    7,    7,    7,    0,    0,    0,
        0,    7,    7,    7,    0,    0,    0,    7,    7,    7,
        7,    7,    7,    7,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   35,   35,   37,   35,   38,   35,   39,
       35,   35,   40,   41,   42,   35,   35,   43,   35,   35,
       44,   45,   46,   47,   48,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   35,   58,   59,   60,   61,
       62,   63,   35,   64,   65,   66,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[77] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    5,    1,    6,    6,    7,
        7,    1,    1,    1,    1,    1,    3,    7,    7,    7,
        7,    7,    7,    8,    8,    8,    8,    8,    8,    8,
        8,    9,    8,    1,    8,    1,    1,    8,    6,    6,
        7,    7,    7,    6,    8,    8,    8,    8,    8,    8,
        9,    8,    8,    9,    8,    9,    9,    9,    8,    9,
        8,    8,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[401] =
    {   0,
        0,    0,  929, 1133, 1133, 1133,  903,   72,    0,  902,
       70,   76, 1133, 1133,  901,   67,   68,   66,   79,   81,
       89,   64,  900,   86,  879,  109,   39,  898,   99,   53,
       58,   74,   93,   98,  102,   70,   80,  100,   97,  113,
       45,  158,  104,  115,  127, 1133,  108, 1133,  154,    0,
      913,  912,  220,  898,  156,  901,    0,  212,  235,  165,
      896,  277,  150,  143,  149,  886,  885,  864,  123,  189,
      192,    0,    0,  152,  160,  161,  154,  153,  181,  169,
      196,  182,  159,  155,  191,  197,  205,  201,  215,  212,
      216,  230,  219,  233,  853,  244,  240,  260,  246,  261,

      264,  255,  259,  302,  272,  273,  278,  322,    0,    0,
      268,  888, 1133,  886,  885,  330,  359,  396,  348,  340,
      299,  881,  333,    0,  401,  353,  309,  297,  339,    0,
      414,  328, 1133,  854,  831,    0,    0,    0,    0,  297,
      320,  321,  339,  341,  218,  298,  348,  330,  378,  358,
      386,  397,  392,  387,  414,  390,  407,  417,  420,  418,
      421,  427,  426,  319,  423,  429,  430,  431,  434,  440,
      442,  441,  443,  444,  447,  453,  450,  492,    0,    0,
      491,  880, 1133, 1133,  494,  544,  581,  497,  501,  497,
     1133,  516,  875, 1133,  481, 1133,  849,  826,  465,  475,

      490,  565,  496,  493, 1133,    0,    0,    0,    0,  513,
      480,  500,  524,  501,  534,  537,  525,  562,  547,  558,
      559,  561,  563,  572,  573,  481,  575,  574,  578,  580,
      576,  526,  592,  596,  599,  600,  582,  603,  606,  608,
      621,    0,    0,  649,  843,  702,  739, 1133,  632, 1133,
      614, 1133,  644,  649,  786,  721,    0,    0,    0,    0,
      612,  614,  615,  631,  630,  632,  633,  634,  635,  640,
      639,  643,  661,  644,  655,  646,  664,  670,  666,  673,
      680,  684,  681,  683,    0,    0,  776,  813, 1133, 1133,
        0,    0,    0,  496,  699,  696,  693,  705,  682,  718,

      728,  729,  719,  700,  730,  731,  733,  757,  739,    0,
      772,  850,  387,    0,  183,    0,  648,  758,  754,  768,
      766,  756,  228,  396,  769,  771,  755,  795,  803,    0,
      887,    0,    0,  773,  704,  804,  791,    0,  924,    0,
        0,  806,  793,  810,    0,    0,    0,  794,  809,  831,
      812,  828,  829,  830, 1133,  978,  987,  996, 1000, 1007,
     1016, 1025, 1034, 1039, 1041, 1043, 1045, 1047, 1054, 1063,
     1067, 1069, 1071, 1073, 1075, 1077, 1079, 1081, 1083, 1085,
     1087, 1089, 1091, 1093, 1095, 1097, 1099, 1101, 1103, 1105,
     1107, 1109, 1111, 1113, 1115, 1117, 1119, 1121, 1123, 1125

    } ;

static const flex_int16_t yy_def[401] =
    {   0,
      355,    1,  355,  355,  355,  355,  355,  356,  357,  355,
      355,  358,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  359,  359,  355,  355,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  355,  355,  356,  355,  360,  357,
      361,  361,  361,  355,  355,  362,  363,  355,  355,  355,
      364,  355,  355,  355,  355,  355,  355,  359,  355,  356,
      358,  365,  366,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,

      359,  359,  359,  359,  359,  359,  359,  356,  367,  368,
      355,  369,  355,  369,  355,  369,  369,  117,  369,  355,
      355,  362,  370,  363,  355,  355,  355,  355,  355,  371,
      364,  355,  355,  355,  355,  372,  373,  374,  375,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  356,  376,  377,
      356,  369,  355,  355,  369,  117,  117,  369,  355,  355,
      355,  355,  370,  355,  355,  355,  355,  355,  371,  371,

      355,  355,  355,  355,  355,  378,  379,  380,  381,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      356,  382,  383,  356,  369,  117,  117,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  384,  385,  386,  387,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  388,  389,  117,  117,  355,  355,
      390,  391,  392,  359,  359,  359,  359,  359,  359,  359,

      359,  359,  359,  359,  359,  359,  359,  359,  359,  393,
      356,  117,  369,  394,  359,  395,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  396,
      117,  397,  398,  359,  359,  359,  359,  399,  117,  400,
      387,  359,  359,  359,  389,  288,  391,  359,  359,  359,
      359,  359,  359,  359,    0,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355

    } ;

static const flex_int16_t yy_nxt[1210] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   13,   17,   18,   19,   20,   21,   21,
       21,   13,   13,   22,   23,   24,   13,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   26,   25,   25,   25,
       25,   26,   25,   13,   27,   13,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   25,   37,   25,   38,   25,
       25,   25,   25,   39,   40,   41,   42,   43,   44,   25,
       25,   25,   13,   45,   13,   13,   48,   46,   52,   46,
       72,   54,   46,   55,   55,   55,   55,   66,   46,   69,
       56,   46,   46,   46,   46,   57,   58,   69,   59,   59,

       60,   60,   69,   46,   58,   73,   62,   62,   62,   62,
       46,   67,   48,   70,   69,  103,   49,   71,   69,   82,
       53,   83,   84,   61,   69,   63,   74,   75,   76,   85,
       64,   94,   77,   95,   78,   86,   79,   69,   80,   81,
       96,   69,   69,   69,   69,   87,   69,   65,   69,   98,
       61,   46,   49,   69,   88,   64,   89,   69,   90,   69,
       92,   97,   70,   93,  136,  106,   71,   91,   99,  100,
      107,  108,  108,   55,   55,   55,   55,  104,  101,  134,
       58,  102,  126,  126,  126,  126,  132,  120,  121,  137,
      133,  133,  121,   48,   52,  109,   69,   69,   69,   69,

       46,  135,   69,   69,   69,   69,  144,  132,  120,  121,
      140,  150,  145,   69,  121,  133,  133,  141,  105,  151,
      110,  142,  143,  111,  114,   69,   69,   69,  115,  125,
      125,  125,  125,   49,  147,   69,   53,  116,  116,  152,
       69,   69,  146,  120,  121,   69,  114,  149,  121,   69,
       58,  148,   59,   59,  126,  126,   69,  153,  154,   69,
       69,  117,   69,   69,  120,  121,  215,  155,  114,  114,
      121,  127,   69,  114,   69,  336,  128,   69,  157,  156,
      114,  158,   95,  114,   69,  114,  118,  114,   69,  119,
       69,  159,   58,  129,   62,   62,   62,   62,  160,   69,

      162,  128,  161,   69,   69,   69,   70,  166,   69,   95,
       71,  171,  169,   63,  163,  167,   69,   69,   64,  181,
      181,  172,   69,  181,  164,  165,   48,  170,  173,  175,
      192,  176,  168,  197,  177,   65,  174,  181,  184,  178,
      178,   69,   69,   64,  123,  195,   69,  185,  185,  194,
      196,  192,  189,  210,  189,  198,  183,  190,  190,  190,
      190,  216,  191,   69,   69,   69,   49,  183,   58,  133,
      126,  126,  126,  126,   69,  196,  186,  186,  186,  186,
      196,  211,  212,   69,  228,   69,  186,  186,  186,  186,
      186,  186,   69,  218,  133,  184,  217,  195,  213,  188,

      188,  214,   69,  188,  191,  196,  219,  186,  186,  186,
      186,  186,  186,  187,  187,  187,  187,  188,  125,  125,
      125,  125,   69,  187,  187,  187,  187,  187,  187,  200,
       69,   69,  120,  121,   69,  222,   69,  121,   95,   95,
       69,   69,   95,  337,  187,  187,  187,  187,  187,  187,
      201,   69,  202,  120,  121,  203,  220,  221,   69,  121,
       95,   69,   69,  223,   69,   69,   95,   69,  225,  224,
       69,   69,  204,   69,   69,   69,  202,  226,   69,   95,
      203,   95,  227,  232,   69,   69,   69,   69,   69,  229,
      231,   69,  230,  236,   69,   48,   48,   69,   95,  233,

      238,  239,  184,  202,  237,  184,  234,  235,  240,  241,
      241,  245,  245,  202,  190,  190,  190,  190,  190,  190,
      190,  190,  196,  191,   69,   69,  251,  202,  249,  248,
      249,  252,  255,  248,  252,   49,   49,  202,  191,  262,
       69,  273,  244,  244,   69,   69,  244,  196,  188,  188,
      248,  251,  188,  264,  256,  248,  252,   69,   95,  252,
      244,  246,  246,  246,  246,  191,  188,  261,   69,   69,
       69,  246,  246,  246,  246,  246,  246,  253,   69,  253,
      191,   69,  254,  254,  254,  254,  263,  278,  265,  266,
      267,   69,  246,  246,  246,  246,  246,  246,  247,  247,

      247,  247,   69,   69,   95,   69,   69,   69,  247,  247,
      247,  247,  247,  247,  268,  269,   69,   69,   69,   69,
       69,  271,   69,   95,   69,   48,   69,  270,  277,  247,
      247,  247,  247,  247,  247,  272,   69,  275,   95,  274,
       69,  276,   95,   69,   69,   95,  280,   69,  279,  281,
       69,  282,   69,   48,  191,  252,   69,  283,   69,   69,
       95,  254,  254,  254,  254,   49,  254,  254,  254,  254,
      296,  284,  295,  297,   69,   69,   69,   69,   69,   69,
      252,  289,  302,   69,   69,  289,  299,   69,   69,  301,
       69,   95,   69,   49,  298,  303,  191,  300,  304,   69,

      244,  244,  289,   95,  244,   69,   95,  289,   69,  305,
       69,  306,   95,   95,   69,   95,   95,   69,  244,  287,
      287,  287,  287,   95,   69,   69,   69,   69,   69,  287,
      287,  287,  287,  287,  287,   95,  307,   69,   95,  309,
       69,  308,  321,   69,   69,  319,   95,  317,   69,   69,
      287,  287,  287,  287,  287,  287,  288,  288,  288,  288,
      318,  320,   69,   69,   95,   95,  288,  288,  288,  288,
      288,  288,   69,   69,   69,   69,   48,   69,  323,  290,
      324,  327,  326,   69,  322,  325,   95,  288,  288,  288,
      288,  288,  288,  312,  312,  312,  312,  329,   69,   69,

       69,   69,   69,  312,  312,  312,  312,  312,  312,  328,
       69,   95,   69,   69,  334,   69,   49,   69,   95,  335,
       95,   95,  290,   95,  312,  312,  312,  312,  312,  312,
      313,  313,  313,  313,   95,   69,  342,   69,   69,   69,
      313,  313,  313,  313,  313,  313,   95,   69,   69,  344,
       69,  184,  343,   69,   69,   95,   69,  348,  350,  351,
      353,  313,  313,  313,  313,  313,  313,  331,  331,  331,
      331,  349,   69,   69,   69,   69,   95,  331,  331,  331,
      331,  331,  331,  352,  250,  250,  123,   95,  183,  205,
      205,  354,  123,  113,  184,   95,  183,   69,  331,  331,

      331,  331,  331,  331,  339,  339,  339,  339,   69,   46,
       46,  130,  123,   46,  339,  339,  339,  339,  339,  339,
      355,  113,   46,   69,   46,   46,   46,   46,  355,  355,
      355,  355,  355,  355,  355,  339,  339,  339,  339,  339,
      339,  346,  346,  346,  346,  355,  355,  355,  355,  355,
      355,  346,  346,  346,  346,  346,  346,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  346,  346,  346,  346,  346,  346,   47,  355,
       47,   47,   47,   47,   47,   47,   47,   50,  355,   50,
       50,   50,   50,   50,   50,   50,   51,   51,   51,  355,

       51,   51,   51,   51,   51,   68,   68,   68,   68,   47,
       47,  355,   47,  355,  355,   47,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  122,  122,  122,  122,  122,
      122,  122,  122,  122,  124,  355,  124,  124,  124,  124,
      124,  124,  124,  131,  131,  131,  138,  138,  139,  139,
      179,  179,  180,  180,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  199,  199,  206,  206,  207,  207,  208,  208,
      209,  209,  242,  242,  243,  243,  257,  257,  258,  258,
      259,  259,  260,  260,  285,  285,  286,  286,  291,  291,

      292,  292,  293,  293,  294,  294,  310,  310,  311,  311,
      314,  314,  315,  315,  316,  316,  330,  330,  332,  332,
      333,  333,  338,  338,  340,  340,  341,  341,  345,  345,
      347,  347,    3,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,

      355,  355,  355,  355,  355,  355,  355,  355,  355
    } ;

static const flex_int16_t yy_chk[1210] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    8,   11,   12,   16,
       27,   18,   17,   18,   18,   18,   18,   22,   22,   41,
       19,   16,   17,   17,   11,   19,   20,   30,   20,   20,

       20,   20,   31,   19,   21,   27,   21,   21,   21,   21,
       24,   24,   47,   26,   36,   41,    8,   26,   32,   30,
       12,   31,   32,   20,   37,   21,   29,   29,   29,   32,
       21,   36,   29,   37,   29,   32,   29,   33,   29,   29,
       37,   39,   34,   29,   38,   33,   35,   21,   43,   39,
       20,   45,   47,   26,   33,   21,   34,   40,   34,   44,
       35,   38,   42,   35,   69,   43,   42,   34,   40,   40,
       44,   49,   49,   55,   55,   55,   55,   42,   40,   64,
       60,   40,   60,   60,   60,   60,   63,   55,   55,   69,
       65,   63,   55,   70,   71,   49,   74,   78,   77,   84,

       45,   64,   42,   83,   75,   76,   77,   65,   55,   55,
       74,   83,   78,   80,   55,   65,   63,   74,   42,   84,
       49,   75,   76,   49,   53,   79,   82,  315,   53,   58,
       58,   58,   58,   70,   80,   85,   71,   53,   53,   85,
       81,   86,   79,   58,   58,   88,   53,   82,   58,   87,
       59,   81,   59,   59,   59,   59,   90,   86,   87,   89,
       91,   53,  145,   93,   58,   58,  145,   88,   53,   53,
       58,   59,  323,   53,   92,  323,   59,   94,   90,   89,
       53,   91,   93,   53,   97,   53,   53,   53,   96,   53,
       99,   92,   62,   59,   62,   62,   62,   62,   94,  102,

       97,   59,   96,  103,   98,  100,  104,   99,  101,   96,
      104,  102,  101,   62,   98,  100,  105,  106,   62,  111,
      111,  103,  107,  111,   98,   98,  108,  101,  105,  106,
      121,  106,  100,  128,  107,   62,  105,  111,  116,  108,
      108,  140,  146,   62,  123,  127,  104,  116,  116,  123,
      127,  121,  120,  140,  120,  128,  119,  120,  120,  120,
      120,  146,  120,  164,  141,  142,  108,  117,  126,  132,
      126,  126,  126,  126,  148,  127,  117,  117,  117,  117,
      129,  141,  142,  143,  164,  144,  117,  117,  117,  117,
      117,  117,  147,  148,  132,  313,  147,  129,  143,  119,

      119,  144,  150,  119,  120,  129,  150,  117,  117,  117,
      117,  117,  117,  118,  118,  118,  118,  119,  125,  125,
      125,  125,  149,  118,  118,  118,  118,  118,  118,  131,
      151,  154,  125,  125,  156,  154,  153,  125,  151,  149,
      324,  152,  156,  324,  118,  118,  118,  118,  118,  118,
      131,  157,  131,  125,  125,  131,  153,  153,  155,  125,
      152,  158,  160,  155,  159,  161,  157,  165,  159,  158,
      163,  162,  131,  166,  167,  168,  131,  161,  169,  160,
      131,  162,  163,  168,  170,  172,  171,  173,  174,  165,
      167,  175,  166,  172,  177,  181,  178,  176,  175,  169,

      174,  176,  185,  199,  173,  188,  170,  171,  177,  178,
      178,  185,  185,  200,  190,  190,  190,  190,  189,  189,
      189,  189,  195,  189,  211,  226,  201,  199,  192,  190,
      192,  201,  203,  190,  204,  181,  178,  200,  192,  211,
      294,  226,  181,  181,  212,  214,  181,  195,  188,  188,
      190,  204,  188,  214,  203,  190,  201,  210,  212,  204,
      181,  186,  186,  186,  186,  189,  188,  210,  213,  217,
      232,  186,  186,  186,  186,  186,  186,  202,  215,  202,
      192,  216,  202,  202,  202,  202,  213,  232,  215,  216,
      217,  219,  186,  186,  186,  186,  186,  186,  187,  187,

      187,  187,  220,  221,  219,  222,  218,  223,  187,  187,
      187,  187,  187,  187,  218,  221,  224,  225,  228,  227,
      231,  223,  229,  220,  230,  241,  237,  222,  231,  187,
      187,  187,  187,  187,  187,  224,  233,  228,  225,  227,
      234,  229,  237,  235,  236,  230,  234,  238,  233,  235,
      239,  236,  240,  244,  249,  251,  261,  238,  262,  263,
      240,  253,  253,  253,  253,  241,  254,  254,  254,  254,
      262,  239,  261,  263,  265,  264,  266,  267,  268,  269,
      251,  254,  268,  271,  270,  254,  265,  272,  274,  267,
      276,  271,  317,  244,  264,  269,  249,  266,  270,  275,

      244,  244,  254,  272,  244,  273,  276,  254,  277,  274,
      279,  275,  317,  273,  278,  277,  279,  280,  244,  246,
      246,  246,  246,  278,  281,  283,  299,  284,  282,  246,
      246,  246,  246,  246,  246,  281,  282,  297,  280,  284,
      296,  283,  299,  295,  304,  297,  296,  295,  335,  298,
      246,  246,  246,  246,  246,  246,  247,  247,  247,  247,
      295,  298,  300,  303,  335,  304,  247,  247,  247,  247,
      247,  247,  301,  302,  305,  306,  311,  307,  301,  256,
      302,  306,  305,  309,  300,  303,  307,  247,  247,  247,
      247,  247,  247,  287,  287,  287,  287,  309,  319,  327,

      322,  308,  318,  287,  287,  287,  287,  287,  287,  308,
      321,  318,  320,  325,  321,  326,  311,  334,  320,  322,
      327,  325,  255,  319,  287,  287,  287,  287,  287,  287,
      288,  288,  288,  288,  326,  337,  334,  343,  348,  328,
      288,  288,  288,  288,  288,  288,  328,  329,  336,  337,
      342,  245,  336,  349,  344,  329,  351,  343,  348,  349,
      351,  288,  288,  288,  288,  288,  288,  312,  312,  312,
      312,  344,  352,  353,  354,  350,  342,  312,  312,  312,
      312,  312,  312,  350,  198,  197,  193,  353,  182,  135,
      134,  352,  122,  115,  114,  354,  112,   95,  312,  312,

      312,  312,  312,  312,  331,  331,  331,  331,   68,   67,
       66,   61,   56,   54,  331,  331,  331,  331,  331,  331,
       52,   51,   28,   25,   23,   15,   10,    7,    3,    0,
        0,    0,    0,    0,    0,  331,  331,  331,  331,  331,
      331,  339,  339,  339,  339,    0,    0,    0,    0,    0,
        0,  339,  339,  339,  339,  339,  339,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  339,  339,  339,  339,  339,  339,  356,    0,
      356,  356,  356,  356,  356,  356,  356,  357,    0,  357,
      357,  357,  357,  357,  357,  357,  358,  358,  358,    0,

      358,  358,  358,  358,  358,  359,  359,  359,  359,  360,
      360,    0,  360,    0,    0,  360,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  363,    0,  363,  363,  363,  363,
      363,  363,  363,  364,  364,  364,  365,  365,  366,  366,
      367,  367,  368,  368,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  371,  371,  372,  372,  373,  373,  374,  374,
      375,  375,  376,  376,  377,  377,  378,  378,  379,  379,
      380,  380,  381,  381,  382,  382,  383,  383,  384,  384,

      385,  385,  386,  386,  387,  387,  388,  388,  389,  389,
      390,  390,  391,  391,  392,  392,  393,  393,  394,  394,
      395,  395,  396,  396,  397,  397,  398,  398,  399,  399,
      400,  400,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,

      355,  355,  355,  355,  355,  355,  355,  355,  355
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[15] =
    {   0,
1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 4 "lex.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

int yycolumn = 1, char_cnt = 0;
int start_line, start_column;
int prev_yylineno;

#define YY_USER_ACTION                                                   \
  start_line = prev_yylineno; start_column = yycolumn;                   \
  char_cnt += yyleng;                                                    \
  if (yylineno == prev_yylineno) yycolumn += yyleng;                     \
  else {                                                                 \
    for (yycolumn = 1; yytext[yyleng - yycolumn] != '\n'; ++yycolumn) {} \
    prev_yylineno = yylineno;                                            \
  }

void record_token(const char *type, const char *text);
void print_statistics();

#define MAX_TOKENS 1000
char *token_names[] = {"EOF", "error", "identifier", "keyword", "punctuator", 
                       "integer constant", "floating constant", "char constant", 
                       "string literal"};
int token_counts[MAX_TOKENS] = {0};
char *token_types[MAX_TOKENS];
int token_type_count = 0;

void record_token(const char *type, const char *text) {
    for (int i = 0; i < token_type_count; i++) {
        if (strcmp(token_types[i], type) == 0) {
            token_counts[i]++;
            printf("%d:%d: <%s, %s>\n", start_line, start_column, type, text);
            return;
        }
    }
    token_types[token_type_count] = strdup(type);
    token_counts[token_type_count++] = 1;
    printf("%d:%d: <%s, %s>\n", start_line, start_column, type, text);
}

void print_statistics() {
    int sum = 0;
    for (int i = 0; i < token_type_count; i++) {
        printf("\n%-10d %s", token_counts[i], token_types[i]);
        sum += token_counts[i];
    }
    printf("\ntotal: %d tokens, %d characters, %d lines\n", sum, char_cnt, start_line);
}
#line 912 "lex.yy.c"
#line 913 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 90 "lex.l"


#line 1133 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 356 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1133 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 92 "lex.l"
{}   // 对于合法的块注释，跳过
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 94 "lex.l"
{
    record_token("error", "Unterminated block comment");
    while (input() != '\n') ; // 跳过第二行，从第三行开始词法分析
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 99 "lex.l"
{
    record_token("error", "invalid octal"); // 记录为错误
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 103 "lex.l"
{
    record_token("error", "Invalid character constant");
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 107 "lex.l"
{
    record_token("error", "Incomplete exponent part");
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 111 "lex.l"
{ 
    record_token("keyword", yytext); 
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 115 "lex.l"
{ 
    record_token("identifier", yytext); 
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 119 "lex.l"
{ 
    record_token("punctuator", yytext); 
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 123 "lex.l"
{ 
    record_token("integer constant", yytext);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 127 "lex.l"
{
    record_token("floating constant", yytext); 
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 131 "lex.l"
{ 
    record_token("char constant", yytext); 
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 135 "lex.l"
{ 
    record_token("string literal", yytext); 
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 139 "lex.l"
{ 
    record_token("error", yytext); 
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 143 "lex.l"
ECHO;
	YY_BREAK
#line 1298 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 356 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 356 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 355);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 143 "lex.l"

int main(int argc, char **argv) {
    FILE *fin;
    prev_yylineno = 0;
    if (argc > 1) {
        fin = fopen(argv[1], "r");
        if (fin == NULL) {
            perror("cannot open file");
            return 1;
        }
        yyset_in(fin);
    }

    int token;
    while ((token = yylex()) != 0) {}

    print_statistics();
    
    if (fin) {
        fclose(fin);
    }
    return 0;
}

