(function(){'use strict';var f={l:function(a,b,c){if("undefined"!=typeof c){var e=f.c();e&&e.saveStyleOverride(a,b,c);a.style[b]=c}},f:function(a,b,c){c?a.classList.add(b):a.classList.remove(b)},w:function(a,b){if("undefined"!=typeof b){var c=f.c();c&&c.saveInitialText(a);a.textContent=b;c&&c.applyStylePreservation(a)}},v:function(a,b){if("undefined"!=typeof b){var c=f.c();c&&c.saveInitialText(a);a.innerHTML=b;c&&c.applyStylePreservation(a)}},show:function(a,b){a.style.display=!b||"string"==typeof b&&"false"==b.toLowerCase()?
"none":""},setAttribute:function(a,b,c){"undefined"!=typeof c&&a.setAttribute(b,c)},c:function(){return document.querySelector("gwd-text-helper")}};window.Binder=f;f.setText=f.w;f.setStyle=f.l;f.setHtml=f.v;f.addOrRemoveClassName=f.f;f.show=f.show;f.setAttribute=f.setAttribute;var h=function(a,b){if(a){var c=b.split(".");return a.map(function(a){if(1==c.length)return a[c[0]];var b=a;c.forEach(function(a){b&&(b=b[a])});return b})}return[]},l=function(a,b){return a?a.join(b||","):""},m={hex:function(a){return a?a.replace(/0x/,"#"):a},limit:function(a,b){return b?a&&a.length&&("string"==typeof b&&(b=parseInt(b,10)),!isNaN(b))?a.slice(0,b):a:a},lowercase:function(a){return a?a.toLowerCase():a}};m.join=l;m.pixelvalue=function(a){if("undefined"!=typeof a)return a+"px"};
m.pluck=h;m.pluckandjoin=function(a,b){return l(h(a,b))};m.uppercase=function(a){return a?a.toUpperCase():a};var p=function(a,b,c){if(c){var e=document.createEvent("CustomEvent");e.initCustomEvent(a,!0,!0,c)}else e=document.createEvent("Event"),e.initEvent(a,!0,!0);b.dispatchEvent(e)};var q=/^bind-/,r=/^style-/,t=/^class-/,u=/^each-/,v=/-([a-z])/g;function w(a){return String(a).replace(v,function(a,c){return c.toUpperCase()})}function x(a){return!(!a||!q.test(a.name))}function y(a){return!(!a||0!=a.name.indexOf("bind-each"))}function z(a){Array.prototype.slice.call(a.attributes).filter(y).forEach(function(b){a.removeAttribute(b.name)})}var A=function(){};goog.inherits(A,HTMLElement);
A.prototype.createdCallback=function(){this.b={text:"setText",html:"setHtml",show:"show"};this.j=!1;this.a=null;this.h=this.u.bind(this)};A.prototype.detachedCallback=function(){B(this)};
A.prototype.bindData=function(a,b){b=b||Array.prototype.slice.call(this.ownerDocument.querySelectorAll("*"));var c=(c=this.ownerDocument.querySelector("meta[name=environment]"))?c.getAttribute("content"):"";this.j="gwd-adwords"==c||"gwd-googleads"==c;B(this);(this.a=this.ownerDocument.querySelector("gwd-font-loader"))&&this.a.startDynamicFontLoading();b.forEach(this.g.bind(this,a));a=!0;this.a&&((a=this.a.endDynamicFontLoading())||this.a.addEventListener("gwdfontsloaded",this.h));return a};
A.prototype.g=function(a,b){if(!b.hasAttribute("gwd-bind-each-template")){for(var c,e=Array.prototype.slice.call(b.attributes),d=e.length,g=0;g<d;g++)if(y(e[g])){c=e[g];break}a=this.o.bind(this,b,a);c?a(c):e.filter(x).forEach(a)}};
A.prototype.o=function(a,b,c){var e=c.name,d=e.replace(q,"");if(r.test(d)){var g=d.replace(r,"");g=f.l.bind(null,a,w(g))}else t.test(d)?(g=d.replace(t,""),g=f.f.bind(null,a,g)):u.test(d)?(g=d.replace(u,""),g=this.m.bind(this,a,g,b)):g=this.b[d]&&"function"==typeof f[this.b[d]]?f[this.b[d]].bind(null,a):window.gwd&&window.gwd.binders&&"function"==typeof window.gwd.binders[d]?window.gwd.binders[d]:f.setAttribute.bind(null,a,d);e=a.getAttribute(e);b=(-1!==e.indexOf("|")?this.s.bind(this,b,e):this.i.bind(this,
b,e)).call(a);"style-font-family"==d&&this.a&&(b=this.a.parseFontList(b));"exit-override-url"==d&&(d=(d=c.value)&&d.match(/product\.\d+/i)?(d=d.match(/product\.(\d+)/i))&&d[1]?parseInt(d[1],10):null:null,null!=d&&a.setAttribute("product-index",d),this.j&&a.setAttribute("exit-id",c.value.replace(/\./g,"_")));g.apply(a,[b])};
A.prototype.m=function(a,b,c,e){var d=a.parentNode;if(d){var g=a.cloneNode(!0);z(g);for(var n=[],k=0;e&&k<e.length;k++)n.push(g.cloneNode(!0));p("gwdbindeachcloned",a,{instances:n});g=this.ownerDocument.createComment("gwd-bind-each-placeholder");d.insertBefore(g,a);d.removeChild(a);C(a);if(e&&0!=e.length){for(k=0;k<e.length;k++)c[b]=e[k],a=n[k],a.setAttribute("gwd-repeat-index",k),c.$index=k,Array.prototype.slice.call(a.querySelectorAll("*")).concat(a).forEach(this.g.bind(this,c)),d.insertBefore(a,
g);delete c[b]}}};var C=function(a){a.setAttribute("gwd-bind-each-template","");Array.prototype.slice.call(a.querySelectorAll("*")).forEach(function(a){a.setAttribute("gwd-bind-each-template","")})};A.prototype.i=function(a,b){if(a){if(b){b=b.replace("[",".");b=b.replace("]","");var c=a;b.split(".").forEach(function(a){c&&(c=c[a])});return c}return a}};
A.prototype.s=function(a,b){if(!b)return a;b=b.split("|");var c=b.shift().trim();a=this.i(a,c);if("undefined"!=typeof a){for(c=0;c<b.length;c++)a=D(this,a,b[c].trim());return a}};var D=function(a,b,c){c=c.split(" ").map(function(a){return a.trim()});var e=c.shift(),d=m[e];c.unshift(b);return d?d.apply(null,c):window.gwd&&window.gwd.formatters&&"function"==typeof window.gwd.formatters[e]?window.gwd.formatters[e].apply(a,c):b};A.prototype.u=function(){B(this);p("bindingfinished",this)};
var B=function(a){a.a&&(a.a.removeEventListener("gwdfontsloaded",a.h),a.a=null)};document.registerElement("gwd-data-binder",{prototype:A.prototype});}).call(this);
