(function(){'use strict';var l,n=function(a,b,c){switch(a.getAttribute(b)){case "true":return!0;case "false":return!1;default:return c}};var p=function(){this.a=[];this.o=10;this.l=!0;this.B=!1};p.prototype.fit=function(a){var b=[];a.forEach(function(a){if(this.a.every(function(b){return b.element!=a})&&!a.hasAttribute("gwd-dont-fit")){var c=q(this,a);this.a.push(c);b.push(c)}},this)};
var t=function(a){a.a.forEach(function(a){r(a)}.bind(a));a.a=[]},u=function(a,b){b.forEach(function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(c.element==a){r(c);this.a.splice(b,1);break}}}.bind(a))},r=function(a){null!=a.u&&(a.element.style.fontSize=a.u);null!=a.v&&(a.element.innerHTML=a.v)},q=function(a,b){var c=window.getComputedStyle(b),d=b.style.fontSize,f=b.innerHTML,e={clientWidth:b.clientWidth,clientHeight:b.clientHeight},g=!1,h=a.l;b.hasAttribute("data-gwd-fit-font-size")&&(h=
"false"!=b.getAttribute("data-gwd-fit-font-size"));var k=w(c.fontSize);c=k||24;var m=parseInt(b.getAttribute("gwd-min-font-size-px"),10);m=isFinite(m)?m:a.o;h=h&&(!k||k>m)&&(b.scrollHeight>e.clientHeight||b.scrollWidth>e.clientWidth);k=!1;if(h){var v=w(window.getComputedStyle(b).fontSize);null!=v&&(g=x(a,b,v));c=y(b,e,m,c);-1==c?(b.style.fontSize=m+"px",k=!0):b.style.fontSize=c+"px"}c=a.B;b.hasAttribute("gwd-fitting-truncate")&&(c="false"!=b.getAttribute("gwd-fitting-truncate"));c&&(k||b.scrollHeight>
e.clientHeight||b.scrollWidth>e.clientWidth)&&(z(a,b,e,null),g=!0);return{element:b,u:h?d:null,v:g?f:null}},y=function(a,b,c,d){return A(a,b,c,d,function(a,b){a.style.fontSize=b+"px"})},z=function(a,b,c,d){if(d&&1!=d.nodeType&&3!=d.nodeType)return!1;var f=d?d:b;if(3==f.nodeType||0==f.children.length){var e=f.textContent;if(""==e)return!1;if(f!=b){f.textContent="\u2026";if(b.scrollHeight>c.clientHeight||b.scrollWidth>c.clientWidth)return!1;f.textContent=e}a=A(b,c,0,e.length,function(a,b){f.textContent=
e.slice(0,b)+"\u2026"}.bind(a));f.textContent=-1==a?"":e.slice(0,a)+"\u2026";return-1!=a}for(d=f.childNodes.length-1;0<=d;d--){var g=f.childNodes[d];if(z(a,b,c,g))return!0;f.removeChild(g)}return!1},A=function(a,b,c,d,f){for(var e=-1;;){var g=Math.floor((c+d)/2);f(a,g);if(a.scrollHeight>b.clientHeight||a.scrollWidth>b.clientWidth){if(g==c)return e;d=g-1}else{e=g;if(c==d)return e;c=g+1}}},x=function(a,b,c){if(b.hasAttribute("gwd-dont-fit"))return!1;for(var d=!1,f=b.children.length,e=0;e<f;e++){var g=
b.children[e],h=window.getComputedStyle(g).fontSize,k=w(h);if(k)g.style.fontSize=k/c+"em",d=!0;else if(h=(h=B.exec(h||""))?parseFloat(h[1]):null)k=h*c;else return!1;g=x(a,g,k);d=d||g}return d},w=function(a){return(a=C.exec(a||""))?parseFloat(a[1]):null},C=/^(\d+|\d*\.\d+)px$/i,B=/^(\d+|\d*\.\d+)em$/i;var D=function(a){var b=!1,c=null;return function(){b=!0;c||(b&&(a(),b=!1),c=setTimeout(function(){c=null;b&&(a(),b=!1)},100))}};var E=function(a){this.A=a;this.g=new WeakMap;this.i=new WeakMap};E.prototype.saveInitialText=function(a){for(var b=document.createNodeIterator(a,NodeFilter.SHOW_TEXT,null,!1),c=null,d;d=b.nextNode();)if(F.test(d.textContent)){c=d;break}if(c&&(b=c.parentNode,b!=a)){a.setAttribute("gwd-dont-fit","");for(c=b;c.parentNode!=a;)c=c.parentNode;this.g.set(a,{f:c,parent:b})}};
E.prototype.applyStylePreservation=function(a){if(this.g.get(a)){a.ownerDocument.compareDocumentPosition(a)&Node.DOCUMENT_POSITION_DISCONNECTED||G(this,a);var b=document.createElement("gwd-attached");a.appendChild(b);var c=function(){b.removeEventListener("attached",c);G(this,a);a.removeChild(b)}.bind(this);b.addEventListener("attached",c)}};
var G=function(a,b){var c=a.g.get(b),d=a.i.get(b)||{};if(c){c.f.style.display="none";b.insertBefore(c.f,b.firstChild);try{u(a.A,[b]);var f=getComputedStyle(c.parent);H.forEach(function(a){var c=f.getPropertyValue(a);!d.hasOwnProperty(a)&&c&&b.style.setProperty(a,c,"")});b.removeAttribute("gwd-dont-fit");a.A.fit([b])}finally{b.removeChild(c.f)}}};E.prototype.saveStyleOverride=function(a,b,c){var d=this.i.get(a)||{};d[b]=c;this.i.set(a,d)};
var H="color font-family font-size font-style font-weight font-stretch text-align white-space".split(" "),F=/[^\s\xA0]/;var I=function(){};goog.inherits(I,HTMLElement);l=I.prototype;l.createdCallback=function(){this.b=new p;this.j=":not(*)";this.h=new E(this.b);this.s=this.F.bind(this);this.c=this.D.bind(this);document.addEventListener("pagetransitionstart",this.s);document.addEventListener("adinitialized",this.c);["data-gwd-fit-font-size","fit-font-size-for-selector","gwd-fitting-truncate","gwd-min-font-size-px"].forEach(this.m,this);this.w=D(this.C.bind(this))};
l.detachedCallback=function(){document.removeEventListener("pagetransitionstart",this.s);document.removeEventListener("adinitialized",this.c);window.removeEventListener("resize",this.w,!1)};l.D=function(){document.removeEventListener("adinitialized",this.c);this.refitAll();window.addEventListener("resize",this.w,!1)};l.F=function(a){"gwd-pagedeck"!=a.target.tagName.toLowerCase()&&"gwd-pagedeck"!=a.target.getAttribute("is").toLowerCase()||this.fit(J(this,a.target))};l.saveInitialText=function(a){this.h.saveInitialText(a)};
l.applyStylePreservation=function(a){this.h.applyStylePreservation(a)};l.saveStyleOverride=function(a,b,c){this.h.saveStyleOverride(a,b,c)};
l.m=function(a){var b=this.getAttribute(a);switch(a){case "data-gwd-fit-font-size":this.b.l=n(this,"data-gwd-fit-font-size",!0);break;case "fit-font-size-for-selector":this.j=b||":not(*)";break;case "gwd-min-font-size-px":a=this.b;b=parseInt(this.getAttribute("gwd-min-font-size-px"),10);isNaN(b)&&(b=10);a.o=b;break;case "gwd-fitting-truncate":this.b.B=n(this,"gwd-fitting-truncate",!1)}};l.fit=function(a){this.b.fit(a||J(this,document))};
var J=function(a,b){return Array.prototype.slice.call(b.querySelectorAll(a.j)).filter(function(a){return a!==this},a)};I.prototype.attributeChangedCallback=function(a){this.m(a)};I.prototype.C=function(){this.refitAll()};I.prototype.refitAll=function(){t(this.b);this.fit()};document.registerElement("gwd-text-helper",{prototype:I.prototype});}).call(this);
